# Generated by Django 4.1.5 on 2023-03-16 05:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='clase')),
                ('sort', models.CharField(blank=True, max_length=4, null=True, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='act')),
                ('internal', models.BooleanField(default=False, verbose_name='int')),
                ('locked', models.BooleanField(default=False, verbose_name='lock')),
                ('replace', models.BooleanField(default=False, verbose_name='repl')),
                ('datet', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha-hora')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha')),
                ('num_int', models.IntegerField(default=0)),
                ('num_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mark', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='nota')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('repository', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Wsite',
                'verbose_name_plural': 'Wsites',
                'ordering': ['sort'],
                'abstract': False,
                'unique_together': {('alias', 'repository')},
            },
        ),
        migrations.CreateModel(
            name='Dataload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='clase')),
                ('sort', models.CharField(blank=True, max_length=4, null=True, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='act')),
                ('internal', models.BooleanField(default=False, verbose_name='int')),
                ('locked', models.BooleanField(default=False, verbose_name='lock')),
                ('replace', models.BooleanField(default=False, verbose_name='repl')),
                ('datet', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha-hora')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha')),
                ('num_int', models.IntegerField(default=0)),
                ('num_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mark', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='nota')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('wsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wsites.wsite')),
            ],
            options={
                'verbose_name': 'Dataload',
                'verbose_name_plural': 'Dataloads',
                'ordering': ['sort'],
                'abstract': False,
                'unique_together': {('wsite', 'alias', 'sort')},
            },
        ),
    ]
