# Generated by Django 4.1.5 on 2024-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='docfile',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Fichero (pdf, xls, doc, svg..)'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='text3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email / web'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='text4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='botón Contenido'),
        ),
        migrations.AlterField(
            model_name='layouti18n',
            name='text3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='email / web'),
        ),
        migrations.AlterField(
            model_name='layouti18n',
            name='text4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='botón Contenido'),
        ),
    ]
