# Generated by Django 4.1.5 on 2024-04-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagei18n',
            name='last_alias',
        ),
        migrations.RemoveField(
            model_name='pagei18n',
            name='level',
        ),
        migrations.RemoveField(
            model_name='pagei18n',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='pagei18n',
            name='root_alias',
        ),
    ]
